### ISSUE TITLE
Can't upload APK with multiple CPU arch

### ISSUE THREAD

**Issue by JPeColCom** [jeduan/playup#14] opened 2016-02-16 15:27 UTC
Each Upload overrides the last. e.g.
upload armv7 with versionCode 1162
upload x86 with versionCode 1164
The APK with versionCode 1162 is canceled.

The createEdit() and commitChanges() methods should wrap multiple uploads to fix this issue.

See: http://developer.android.com/google/play/publishing/multiple-apks.html

**Comment by c-h-** [comment] 2016-02-24 23:31
I had the same issues. I forked the repo and got it working with some very small changes at [https://github.com/AppCow/playup](https://github.com/AppCow/playup).

The biggest difference is that the 'apk' argument can be a string or array of paths. Internally it uploads the apks with a Promise.all. There are a few other minor changes but that's it.

**Comment by ignaciohita** [comment] 2016-03-07 11:16
Hello,

Thanks for the modified plugin, but I can't use it, I'm lost.

Is possible to use with the CLI? I have tried but no luck. It seems that the CLI is now providing multi APK functionality.

How can install it to use it with Gulp? I have tried but if I install using this command:
`npm install https://github.com/AppCow/playup.git `

It's installed:
`âââ playup@1.0.2 (git+https://github.com/AppCow/playup.git#8511cba8ffb8139af802ff765f41b50cb9cb89b8) `

But when I am going to use it, I'm getting this error:
` Error: Cannot find module 'playup' `

It's not happening when I use "normal playup", can you please explain how to use your modified version of playup?

Thanks a lot!

**Comment by c-h-** [comment] 2016-04-16 18:02
Hey @ignaciohita just saw this comment.

Since the changes in the fork have been merged back in I would recommend using this original repo instead.

To get it working if it's installed into a project rather than globally I had to run the following commands:

```
cd node_modules/playup/
npm install
```

Once you do that the files should all be there for you to `require('playup');` in your project. Hope that helps!

I have not used this package from CLI nor installed it globally.

**Comment by alexblack** [comment] 2016-07-29 23:20
+1

**Comment by mayconjcm** [comment] 2016-11-28 11:58
@c-h- Do you have some example, about the Multiple CPU APK? I'm passing a array, but is'nt working. 
I'm getting the error: **Error: APK does not contain 'AndroidManifest.xml'**

The problem is, the node-apk-parser/lib/apkreader.js:39:15 isn't trying to find AndroidManifest in each path of array, but interpreting the array like a unique string. 
I wanna know if could you help me.

I am using this code:

`googlePlayPublisher.upload([
				'57e587bcea01cb4d9e077ef0_android4_x86.apk',
				'57e587bcea01cb4d9e077ef0_android4_armv7.apk'
			], {
				track: 'alpha'
			}).then((data) => {
				console.log(data);
				res.json(data);
			}, (err) => {
				console.log(err);
				res.json(err);
			});`

Thnks!

**Comment by c-h-** [comment] 2016-11-28 16:30
@mayconjcm it's been awhile since I've used this project but this is the code I'm using:

```javascript
publisher.upload(apks, {
          recentChanges: {
            'en-US': 'V2 app build system test'
          },
          track: 'alpha'
        }).then(function(data){
          console.log(' > %s version %d is up!', data.packageName, data.versionCode)
          callback();
        }).catch(function(e){
          gutil.log(e);
        });
```

where `apks` is an array of local paths to apk files.

Try this - my package.json is actually referencing the github repository instead of npm - I believe the merged in contents that enables arrays of apks was never published to NPM.

If you `npm un -S playup && npm i -S https://github.com/jeduan/playup.git` and run your code again perhaps it'll work.

Check inside your node_modules/playup for the changes in this diff to see if multi-apk uploads is enabled in your version of playup: https://github.com/jeduan/playup/commit/f2cc0f390a3248e48e44048ea3f718799a8b4042

**Comment by jeduan** [comment] 2016-11-28 17:11
just published v1.1 with the latest master, so you should be good to go

**Comment by mayconjcm** [comment] 2016-11-28 20:23
Problem solved!!

@c-h- Thank you so much for the Pull Request, this feature is really really important!
@jeduan Your repo saved my day. Thanks for the quick npm release too!

Im attaching the results :+1: 

![captura de tela de 2016-11-28 18 16 54](https://cloud.githubusercontent.com/assets/14805864/20684564/aadb297a-b597-11e6-8bd1-6a13f362f738.png)

**Comment by jeduan** [comment] 2016-11-28 20:24
👍

**Closed by jeduan** 2016-11-28 20:24 UTC
